### ISSUE TITLE
Doesn't support workspaces

### ISSUE THREAD

**Issue by franziskuskiefer** [Kachoc/charon#1]
In workspaces the `target` directory is not in the same directory as the crate. So this will always fail.

https://github.com/Kachoc/charon/blob/7154478ad283b2a8b5fc4a409187c86137505223/charon/src/main.rs#L405

**Comment by Kachoc** [comment]
Thanks for reporting this! I just pushed a commit (in the `main` branch)  to retrieve the target directory from the manifest. Could you confirm that it fixes the issue?

**Comment by franziskuskiefer** [comment]
Yes, this appears to be fixed. Thanks!
